version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.1.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
          name: Install Client
          command: |
            npm run client:install
      - run:
          name: Install Server
          command: |
            npm run server:install
      - run:
          name: Build Client
          command: |
            npm run client:build
      - run:
          name: Build Server
          command: |
            npm run server:build
      - run:
          name: Deploy Client
          command: |
            npm run client:deploy
      - run:
          name: Deploy Server
          command: |
            npm run server:deploy
