version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.1.0
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install Client
          command: |
            npm run client:install
      - run:
          name: Install Server
          command: |
            npm run server:install
      - run:
          name: Build Client
          command: |
            npm run client:build
      - run:
          name: Build Server
          command: |
            npm run server:build
      - run:
          name: Deploy Client
          command: |
            npm run client:deploy
      - run:
          name: Deploy Server
          command: |
            eb init udagram-api --platform node.js 
            eb create --sample udagram-api-dev
            eb deploy udagram-api-dev
            eb status